version: '2'

services:

  szte-php-fpm:
    build: ./php-fpm
    container_name: szte-php-fpm
    volumes:
      - ./code:/code
    links:
      - szte-postgres:db
    depends_on:
      - szte-postgres
    networks:
       - szte-network
      
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8123:80
    links:
      - szte-php-fpm
    volumes:
      - ./nginx/sites:/etc/nginx/sites
      - ./code:/code
    depends_on:
      - szte-php-fpm
    networks:
      - szte-network

  szte-postgres:
    build: ./postgres
    container_name: szte-postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=szte
      - POSTGRES_USER=szte
      - POSTGRES_PASSWORD=titok
    ports:
      - 5432:5432
    networks:
       - szte-network
      
networks:
   szte-network:
        driver: bridge
